In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3])

arr2 = np.array([4, 5, 6])

In [7]:
arr1 + arr2

array([5, 7, 9])

In [8]:
arr1 * arr2

array([ 4, 10, 18])

In [10]:
arr1 // arr2

array([0, 0, 0])

In [12]:
arr2 / arr1

array([4. , 2.5, 2. ])

In [13]:
arr1 % arr2

array([1, 2, 3])

In [14]:
arr2 % arr1

array([0, 1, 0])

In [16]:
arr2 - arr1

array([3, 3, 3])

In [18]:
arr1 - arr2

array([-3, -3, -3])

In [22]:
arr1_2d = np.array([[1,2,3], [4,5,6]])

arr2_2d = np.array([[4, 5, 6] , [7,8,9]])

In [23]:
arr1_2d + arr2_2d

array([[ 5,  7,  9],
       [11, 13, 15]])

In [24]:
arr1_2d - arr2_2d

array([[-3, -3, -3],
       [-3, -3, -3]])

In [25]:
arr1_2d = np.array([[1,2,3], [4,5,6] , [4,5,6]])

arr2_2d = np.array([[4, 5, 6] , [7,8,9] , [4,5,6] ])

In [26]:
arr1_2d - arr2_2d

array([[-3, -3, -3],
       [-3, -3, -3],
       [ 0,  0,  0]])