In [1]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

In [3]:
## Copy Function --------------------

new_arr = arr.copy()

new_arr

array([1, 2, 3, 4, 5])

In [9]:
new_arr[0]  = 10

In [5]:
new_arr

array([10,  2,  3,  4,  5])

In [8]:
arr[1] = 20
arr

array([ 1, 20,  3,  4,  5])

In [10]:
new_arr

array([10,  2,  3,  4,  5])

In [11]:
arr

array([ 1, 20,  3,  4,  5])

In [12]:
## View Function -----------------------------------------

arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [14]:
view_arr = arr1.view()
view_arr

array([1, 2, 3])

In [16]:
view_arr[0] = 100
view_arr

array([100,   2,   3])

In [17]:
arr1

array([100,   2,   3])

In [20]:
arr1[2] = 400

arr1

array([100,   2, 400])

In [21]:
view_arr

array([100,   2, 400])

In [23]:
view_arr[1:2] = 100
view_arr

array([100, 100, 400])

In [24]:
arr1

array([100, 100, 400])