What is NumPy?


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [1]:
# Installation of NumPy

pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# NumPy as np

mport numpy as np

arr  = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [5]:
list = [10,20,30,40,50]

arr = np.array(list)

print(arr)

type(arr)

[10 20 30 40 50]


numpy.ndarray

In [6]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [7]:
# NumPy Creating Arrays

import numpy as np

arr = np.array([2,5,8,9,6,3])

print(arr)

print(type(arr))

[2 5 8 9 6 3]
<class 'numpy.ndarray'>


In [8]:
# 2D Array

lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]


np.array([lst1 , lst2 , lst3])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr = np.array([lst1 , lst2 , lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [11]:
arr.shape

(3, 5)

In [17]:
#  NumPy Array Indexing

arr1 = np.array([1,2,3,4,5])

print(arr1)

# indexing

arr1[1]


[1 2 3 4 5]


2

In [18]:
arr1[1:3] # last element = n-1 => 3-1 = 2

array([2, 3])

In [19]:
arr1[1:]

array([2, 3, 4, 5])

In [22]:
arr1[-1]

5

In [21]:
arr1[:-1]

array([1, 2, 3, 4])

In [23]:
arr1[::]

array([1, 2, 3, 4, 5])

In [24]:
arr1[::-1]

array([5, 4, 3, 2, 1])

In [25]:
arr1[::-2]

array([5, 3, 1])

In [27]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]


arr = np.array([lst1 , lst2 , lst3])

print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [28]:
arr[: , 1]  # [row , col] => [: , 1]

array([2, 3, 4])

In [30]:
arr[1:,1:]

array([[3, 4, 5, 6],
       [4, 5, 6, 7]])

In [31]:
arr[1: , 1:3]

array([[3, 4],
       [4, 5]])

In [32]:
arr[1: , 3:]

array([[5, 6],
       [6, 7]])

In [33]:
arr[:: , 3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [34]:
arr[: , 4:]

array([[5],
       [6],
       [7]])

In [36]:
arr[: , :2]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [40]:
# EDA 
arr1

array([1, 2, 3, 4, 5])

In [41]:
arr1[arr1<2]

array([1])

In [42]:
## Reshape -----------------------------------------------

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [44]:
## Reshape -----------------------------------------------

arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [45]:
## arange uesed to create an array 

np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [49]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
## Random number function

np.random.randint(1,10)

7

In [64]:
np.random.randint(1,10,5)

array([7, 4, 8, 4, 4])

In [65]:
np.random.randint(1,10,6).reshape(2,3)

array([[1, 3, 7],
       [4, 9, 6]])

In [66]:
np.random.randn(2,3)

array([[ 0.53400866,  0.63997253,  0.35334688],
       [-1.60988375, -0.55420902,  1.62871193]])

In [69]:
np.random.random_sample((4,7))

array([[0.02649937, 0.42897765, 0.86975703, 0.71557475, 0.20789109,
        0.00792548, 0.31855989],
       [0.88138669, 0.48562419, 0.65423743, 0.74033885, 0.33043334,
        0.2026999 , 0.86415042],
       [0.23957571, 0.14403562, 0.71672192, 0.07673887, 0.82165229,
        0.57482818, 0.50002159],
       [0.41694635, 0.66081666, 0.43556776, 0.32178342, 0.27519181,
        0.6119938 , 0.65606896]])