In [6]:
pip install numpy


     --------------------------------------- 15.8/15.8 MB 23.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

In [12]:
myarr = np.array([1,2,3,4,5,6] , np.int8)
myarr

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [16]:
myarr[0]

1

In [20]:
## 2D Array ------------------------

myarr = np.array( [ [1,2,3,4,5,6] ] )   ## (row , col) => (0,0)
myarr[0 , 0]

1

In [22]:
## Shape of array ---------------------

myarr.shape

(1, 6)

Array Creation : Convertion from other python structures....

In [24]:
arrlist = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )

arrlist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arrlist.dtype

dtype('int32')

In [26]:
arrlist.shape

(3, 3)

In [27]:
arrlist.size

9

In [28]:
np.array({32,25,12})


array({32, 25, 12}, dtype=object)

In [30]:
## Zero function

zero = np.zeros( (2,5) )

zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
zero.dtype

dtype('float64')

In [32]:
zero.shape

(2, 5)

In [34]:
## Arange function

rng = np.arange(10)

rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
## Linspace function

lspace = np.linspace(1,5,4)

lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [38]:
emp = np.empty((4,9))
emp

array([[1.06949734e-311, 1.19563886e-321, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.16097020e-028,
        1.26104862e-076, 2.92732915e-028, 9.15782077e-072],
       [1.04917183e-153, 5.23081515e-143, 3.63018753e+179,
        5.70197252e-066, 6.16179515e-042, 6.11380293e+169,
        7.10913604e-144, 3.59751658e+252, 3.42032083e+169],
       [3.51147619e+151, 1.04816985e-142, 9.30537467e+199,
        4.10977735e-061, 1.00567951e-047, 1.32654760e-047,
        1.04969509e-046, 1.93410377e-076, 1.47762365e+248],
       [1.16096346e-028, 9.51336254e+169, 6.86651733e-091,
        1.22501944e-046, 2.80597368e-032, 4.26416162e-096,
        4.82337433e+228, 5.60230188e-067, 1.58268989e-319]])

In [39]:
emp_like = np.empty_like(lspace)

emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [41]:
ide = np.identity(45)

ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
ide.shape

(45, 45)

In [45]:
arr = np.arange(99)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr_new = arr.reshape(3,33)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [53]:
arr1 = arr_new.ravel()

In [54]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr1.shape

(99,)

In [56]:
x = [[1,2,3] , [4,5,6] , [7,8,9]]

arr = np.array(x)

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr.sum(axis = 0)

array([12, 15, 18])

In [60]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [61]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
arr.flat

In [63]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [64]:
arr.size

9

In [66]:
arr.ndim

2

In [67]:
arr.nbytes

36

In [75]:
one = np.array([10,20,30,40,50])

one

array([10, 20, 30, 40, 50])

In [76]:
one .argmax()

4

In [73]:
one.argmin()

0

In [77]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [78]:
## In 2D array ------------------------

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr.argmax()

8

In [83]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [80]:
arr.argmin()

0

In [84]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [ ]:
arr.argmin()

In [82]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [85]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [88]:
arr2 = np.array([ [10,20,30] , [40,50,60] , [70,80,90] ])

arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
arr + arr2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [90]:
arr * arr2

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [94]:
arr.sum()

45

In [95]:
arr.max()

9

In [96]:
arr.min()

1

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [100]:
np.count_nonzero(arr)

9

In [101]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [102]:
import sys

In [104]:
py_ar = [0,4,55,2]

In [105]:
np_ar = np.array(py_ar)

In [106]:
sys.getsizeof(1) * len(py_ar)

112

In [107]:
np_ar.itemsize * np_ar.size

16

In [108]:
np_ar.tolist() ##  numpy array into python list -----

[0, 4, 55, 2]