In [1]:
import numpy as np 


arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [2]:
for i in range(len(arr)):
    print(arr[i])

0
1
2
3
4
5
6
7
8
9
10


In [4]:
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
    print(i)
   

[1 2 3]
[4 5 6]


In [5]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [6]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6


In [7]:
for i in arr:
    print(np.sum(i))

6
15


In [8]:
for i in enumerate(arr):
    print(i)

(0, array([1, 2, 3]))
(1, array([4, 5, 6]))


In [10]:
for index , row in enumerate(arr):
    print(f'Row : {index + 1} Sum: {np.sum(row)}')

Row : 1 Sum: 6
Row : 2 Sum: 15


In [11]:
for index , row in enumerate(arr):
    print(f'Row : {index + 1} Min: {np.min(row)}')

Row : 1 Min: 1
Row : 2 Min: 4


In [ ]:
for index , row in enumerate(arr):
    print(f'Row : {index + 1} Sum: {np.sum(row)}')

In [12]:
for i , row in enumerate(arr):
    all_positive = np.all(row > 0)
    print(f'the all element in row {i+1} are positive: {all_positive}')

the all element in row 1 are positive: True
the all element in row 2 are positive: True


In [13]:
for i in arr.T:
    print(i)

[1 4]
[2 5]
[3 6]


In [14]:
for i in arr.transpose():
    print(i)

[1 4]
[2 5]
[3 6]


In [15]:
for i in np.ndenumerate(arr):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


In [21]:
arr1 = np.arange(0,11)
print(arr1)

for i , col in np.ndenumerate(arr1):
    print(f'index {i} column {col}')

[ 0  1  2  3  4  5  6  7  8  9 10]
index (0,) column 0
index (1,) column 1
index (2,) column 2
index (3,) column 3
index (4,) column 4
index (5,) column 5
index (6,) column 6
index (7,) column 7
index (8,) column 8
index (9,) column 9
index (10,) column 10


In [24]:
for i in np.ndindex(arr.shape):
    print(i)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


In [26]:
for i  in np.ndindex(arr1.shape):
    print(f'index {i}')

index (0,)
index (1,)
index (2,)
index (3,)
index (4,)
index (5,)
index (6,)
index (7,)
index (8,)
index (9,)
index (10,)
