In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
reshaped = arr.reshape(2,3)

reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.ravel(reshaped)

array([1, 2, 3, 4, 5, 6])

In [6]:
reshaped.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
arr1 = np.array([1,2,3])

arr1

array([1, 2, 3])

In [9]:
arr2 = np.array([4,5,6])
arr2

array([4, 5, 6])

In [10]:
arr = np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [11]:
np.concatenate((arr1 , arr2) , axis = 0)

array([1, 2, 3, 4, 5, 6])

In [13]:
np.vstack((arr1 , arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.split(arr3 , [1] , axis=0)

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [17]:
np.split(arr3 , [1] , axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [18]:
np.array_split(arr3, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [22]:
np.vsplit(arr3, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [24]:
np.hsplit(arr3, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [25]:
arr4 = np.array([1,2,3,4,5])

np.append(arr4, 6)

array([1, 2, 3, 4, 5, 6])

In [27]:
np.insert(arr4, 1, [1, 2, 3])

array([1, 1, 2, 3, 2, 3, 4, 5])

In [28]:
arr4

array([1, 2, 3, 4, 5])

In [29]:
arr4.astype(float)

array([1., 2., 3., 4., 5.])

In [32]:
float_val =np.array([1., 2., 3., 4., 5.]) 

num = float_val.astype(int)

num

array([1, 2, 3, 4, 5])