In [131]:
import pandas as pd
import numpy as np

s = pd.Series([1,2,3,4,5,6,7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [132]:
s = pd.Series([1,2,3,4,5,6,7]  , index = ['a','b','c','d','e','f','g'])

s


a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [133]:
dist = {'a':1,'b':2,'c':3}
print(pd.Series(dist))

a    1
b    2
c    3
dtype: int64


In [134]:
np.random.rand(10,5)

array([[0.53074994, 0.40450488, 0.30351051, 0.54661602, 0.96953155],
       [0.77270457, 0.59632186, 0.86051137, 0.08653191, 0.75852587],
       [0.61571431, 0.71598828, 0.2604936 , 0.30919861, 0.78966602],
       [0.95267454, 0.01048275, 0.75181623, 0.48846176, 0.14398552],
       [0.39324849, 0.7705948 , 0.20917483, 0.7652689 , 0.89940455],
       [0.79264877, 0.99211177, 0.49546946, 0.59941376, 0.42597234],
       [0.8815447 , 0.21988945, 0.18104944, 0.61332951, 0.44286014],
       [0.17989266, 0.63983732, 0.04455639, 0.70662556, 0.08223702],
       [0.10795277, 0.22196993, 0.54832432, 0.03071795, 0.20627591],
       [0.73750072, 0.67855991, 0.70839568, 0.64767441, 0.89704633]])

In [135]:
df = pd.DataFrame(np.random.rand(10,5) , columns=['col1' , 'col2' , 'col3' , 'col4' , 'col5'])
df

col1      col2      col3      col4      col5
0  0.865208  0.107405  0.588685  0.884368  0.655121
1  0.341628  0.875955  0.655527  0.306544  0.470702
2  0.389971  0.023821  0.483588  0.391625  0.261675
3  0.666852  0.063783  0.072817  0.098053  0.457998
4  0.571674  0.569822  0.721703  0.889887  0.999787
5  0.516682  0.538586  0.753562  0.920763  0.935186
6  0.403243  0.660961  0.485759  0.083480  0.913631
7  0.876094  0.173733  0.647211  0.673876  0.729236
8  0.835361  0.591019  0.747596  0.147213  0.808612
9  0.251235  0.012169  0.771233  0.881652  0.649145

In [136]:

df['total_col'] = df['col1'] + df['col2'] + df['col3'] + df['col4'] + df['col5'] 

df

col1      col2      col3      col4      col5  total_col
0  0.865208  0.107405  0.588685  0.884368  0.655121   3.100787
1  0.341628  0.875955  0.655527  0.306544  0.470702   2.650357
2  0.389971  0.023821  0.483588  0.391625  0.261675   1.550680
3  0.666852  0.063783  0.072817  0.098053  0.457998   1.359503
4  0.571674  0.569822  0.721703  0.889887  0.999787   3.752874
5  0.516682  0.538586  0.753562  0.920763  0.935186   3.664778
6  0.403243  0.660961  0.485759  0.083480  0.913631   2.547072
7  0.876094  0.173733  0.647211  0.673876  0.729236   3.100151
8  0.835361  0.591019  0.747596  0.147213  0.808612   3.129801
9  0.251235  0.012169  0.771233  0.881652  0.649145   2.565434

In [137]:
s = df['col1']
type(s)

pandas.core.series.Series

In [138]:
data = pd.read_excel('ESD.xlsx')
data

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country       City  Exit Date  
0       0.15  United States    Seattle 2021-10-16  
1       0.00          China  Chongqing        NaT  
2       0.20  United States    Chicago        NaT  
3       0.07  United States    Chicago        NaT  
4       0.00  United States    Phoenix        NaT  
..       ...            ...        ...        ...  
995     0.00  United States   Columbus        NaT  
996     0.00          China    Chengdu 2018-01-08  
997     0.15  United States      Miami        NaT  
998     0.00          China    Chengdu        NaT  
999     0.31  United States      Miami        NaT  

[1000 rows x 14 columns]

In [139]:
data.drop(columns='City', inplace= True)



In [140]:
data

EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT   
1    E04105    Theodore Dinh       Technical Architect          IT   
2    E02572     Luna Sanders                  Director     Finance   
3    E02832  Penelope Jordan  Computer Systems Manager          IT   
4    E01639        Austin Vo               Sr. Analyst     Finance   
..      ...              ...                       ...         ...   
995  E03094     Wesley Young               Sr. Analyst   Marketing   
996  E01909     Lillian Khan                   Analyst     Finance   
997  E04398      Oliver Yang                  Director   Marketing   
998  E02521      Lily Nguyen               Sr. Analyst     Finance   
999  E03545      Sofia Cheng            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country  Exit Date  
0       0.15  United States 2021-10-16  
1       0.00          China        NaT  
2       0.20  United States        NaT  
3       0.07  United States        NaT  
4       0.00  United States        NaT  
..       ...            ...        ...  
995     0.00  United States        NaT  
996     0.00          China 2018-01-08  
997     0.15  United States        NaT  
998     0.00          China        NaT  
999     0.31  United States        NaT  

[1000 rows x 13 columns]

In [141]:
data.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
Exit Date        915
dtype: int64

In [142]:
data.duplicated().sum()

0

In [143]:
data['Department'].unique

<bound method Series.unique of 0              IT
1              IT
2         Finance
3              IT
4         Finance
          ...    
995     Marketing
996       Finance
997     Marketing
998       Finance
999    Accounting
Name: Department, Length: 1000, dtype: object>

In [144]:
cm = [i.split()[0] for i in data['Full Name']]

In [145]:
cm

['Emily',
 'Theodore',
 'Luna',
 'Penelope',
 'Austin',
 'Joshua',
 'Ruby',
 'Luke',
 'Easton',
 'Madeline',
 'Savannah',
 'Camila',
 'Eli',
 'Everleigh',
 'Robert',
 'Isabella',
 'Bella',
 'Camila',
 'David',
 'Adam',
 'Elias',
 'Eva',
 'Logan',
 'Leonardo',
 'Mateo',
 'Jose',
 'Abigail',
 'Wyatt',
 'Carson',
 'Dylan',
 'Ezekiel',
 'Dominic',
 'Angel',
 'Mateo',
 'Caroline',
 'Nora',
 'Adeline',
 'Jackson',
 'Riley',
 'Leah',
 'Owen',
 'Kennedy',
 'John',
 'William',
 'Sadie',
 'Gabriel',
 'Wyatt',
 'Eva',
 'Dominic',
 'Lucy',
 'Everleigh',
 'Leilani',
 'Peyton',
 'John',
 'Rylee',
 'Piper',
 'Stella',
 'Addison',
 'Zoey',
 'John',
 'Ava',
 'Natalia',
 'Skylar',
 'Christian',
 'Penelope',
 'Piper',
 'Everly',
 'Aurora',
 'Penelope',
 'Anna',
 'William',
 'Jade',
 'Isla',
 'David',
 'Thomas',
 'Miles',
 'Mila',
 'Benjamin',
 'Samuel',
 'John',
 'Joseph',
 'Jose',
 'Parker',
 'Everleigh',
 'Lincoln',
 'Willow',
 'Jack',
 'Genesis',
 'Eliza',
 'Gabriel',
 'Jack',
 'Everly',
 'Amelia',
 '

In [146]:
data.drop(columns=['Full Name'], inplace=True)
data.insert(loc=1, column='name' , value=cm)

In [147]:
data

EEID      name                 Job Title  Department  \
0    E02387     Emily                Sr. Manger          IT   
1    E04105  Theodore       Technical Architect          IT   
2    E02572      Luna                  Director     Finance   
3    E02832  Penelope  Computer Systems Manager          IT   
4    E01639    Austin               Sr. Analyst     Finance   
..      ...       ...                       ...         ...   
995  E03094    Wesley               Sr. Analyst   Marketing   
996  E01909   Lillian                   Analyst     Finance   
997  E04398    Oliver                  Director   Marketing   
998  E02521      Lily               Sr. Analyst     Finance   
999  E03545     Sofia            Vice President  Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country  Exit Date  
0       0.15  United States 2021-10-16  
1       0.00          China        NaT  
2       0.20  United States        NaT  
3       0.07  United States        NaT  
4       0.00  United States        NaT  
..       ...            ...        ...  
995     0.00  United States        NaT  
996     0.00          China 2018-01-08  
997     0.15  United States        NaT  
998     0.00          China        NaT  
999     0.31  United States        NaT  

[1000 rows x 13 columns]

In [148]:
data['Department'].value_counts()

Department
IT                 241
Engineering        158
Sales              140
Human Resources    125
Finance            120
Marketing          120
Accounting          96
Name: count, dtype: int64

In [149]:
def replacess(a,b):
    data['Department'].replace(a, b , inplace=True)


replacess('IT', 'Information Technology')



C:\Users\mdaza\AppData\Local\Temp\ipykernel_6280\4187074179.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Department'].replace(a, b , inplace=True)


In [150]:
data

EEID      name                 Job Title              Department  \
0    E02387     Emily                Sr. Manger  Information Technology   
1    E04105  Theodore       Technical Architect  Information Technology   
2    E02572      Luna                  Director                 Finance   
3    E02832  Penelope  Computer Systems Manager  Information Technology   
4    E01639    Austin               Sr. Analyst                 Finance   
..      ...       ...                       ...                     ...   
995  E03094    Wesley               Sr. Analyst               Marketing   
996  E01909   Lillian                   Analyst                 Finance   
997  E04398    Oliver                  Director               Marketing   
998  E02521      Lily               Sr. Analyst                 Finance   
999  E03545     Sofia            Vice President              Accounting   

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0    Research & Development  Female      Black   55 2016-04-08         141604   
1             Manufacturing    Male      Asian   59 1997-11-29          99975   
2       Speciality Products  Female  Caucasian   50 2006-10-26         163099   
3             Manufacturing  Female  Caucasian   26 2019-09-27          84913   
4             Manufacturing    Male      Asian   55 1995-11-20          95409   
..                      ...     ...        ...  ...        ...            ...   
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427   
996     Speciality Products  Female      Asian   44 2010-05-31          47387   
997     Speciality Products    Male      Asian   31 2019-06-10         176710   
998     Speciality Products  Female      Asian   33 2012-01-28          95960   
999               Corporate  Female      Asian   63 2020-07-26         216195   

     Bonus %        Country  Exit Date  
0       0.15  United States 2021-10-16  
1       0.00          China        NaT  
2       0.20  United States        NaT  
3       0.07  United States        NaT  
4       0.00  United States        NaT  
..       ...            ...        ...  
995     0.00  United States        NaT  
996     0.00          China 2018-01-08  
997     0.15  United States        NaT  
998     0.00          China        NaT  
999     0.31  United States        NaT  

[1000 rows x 13 columns]

In [151]:
q1 = data['Annual Salary'].quantile(0.25)
q3 = data['Annual Salary'].quantile(0.75)

iqr = q3 - q1

ll = q1 - 1.5 * iqr
ul = q3 + 1.5 * iqr

outliers = data[(data['Annual Salary'] < ll) | (data['Annual Salary'] > ul)]
outliers

Empty DataFrame
Columns: [EEID, name, Job Title, Department, Business Unit, Gender, Ethnicity, Age, Hire Date, Annual Salary, Bonus %, Country, Exit Date]
Index: []

In [152]:
l = [1,2,3,4,5,6,7]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [153]:
type(arr)

numpy.ndarray

In [154]:
radius = [2,3,4,5,6]
arr = np.array(radius)
area = np.pi * arr ** 2

area

array([ 12.56637061,  28.27433388,  50.26548246,  78.53981634,
       113.09733553])

In [155]:
arr = np.arange(1,10)

In [156]:
arr.ndim

1

In [157]:
arr.shape

(9,)

In [158]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
arr.mean()

5.0

In [160]:
arr.std()

2.581988897471611

In [162]:
name = ['azaz' , 'lux' , 'raj' , 'harshit']
marks = [50 , 60 , 70 , 80]
grade = ['A' , 'B' , 'C' , 'D']

pd.DataFrame({i[0]:i[1:] for i in zip(name , marks , grade)})

azaz lux raj harshit
0   50  60  70      80
1    A   B   C       D